### ISSUE TITLE
Rework Dialogue System

### ISSUE THREAD

**Issue by acedogblast** [acedogblast/Project-Uranium-Godot#9]
The whole dialoge system needs to be reworked. The current system was just a quick and dirty mess I put together. The new one should be able to:

- [ ] Take in a long string and parse into multiple 2 liners to prevent overflowing the dialogue box.
- [ ] Get dialogue from an external file outside of code.
- [ ] Support color and bold/italicized text.
- [ ] Recognize when to have short pauses within text.

**Comment by acedogblast** [comment]
The last part can be omitted if it is too difficult to implement and use.

**Comment by Ev1lbl0w** [comment]
I am currently working on this. I will need to know how will the dialogues be defined on the files.

I have investigated how this is done and I found a system called Yarn. Basically the files are written in a simple language and then parsed by the game. The syntax can be found [here](https://github.com/YarnSpinnerTool/YarnSpinner/blob/master/Documentation/YarnSpinner-Dialogue/Yarn-Syntax.md). Honestly it's going to be much easier to make a parser for a *plain-text* file, rather than other files like `JSON`.

**Comment by Ev1lbl0w** [comment]
I am currently working on this. I will need to know how will the dialogues be defined on the files.

I have investigated how this is done and I found a system called Yarn. Basically the files are written in a simple language and then parsed by the game. The syntax can be found [here](https://github.com/YarnSpinnerTool/YarnSpinner/blob/master/Documentation/YarnSpinner-Dialogue/Yarn-Syntax.md). Honestly it's going to be much easier to make a parser for a *plain-text* file, rather than other files like `JSON`.

**Comment by acedogblast** [comment]
Yarn seems too specific for our use case. I say we should just stick to what Godot natively supports which is to use CSV files. This way if we get a translator in the future all he/she needs to do it to edit only one file. The downside with this solution is that we still need to write a parser that can recognize custom macros to indicate bold/italicized/color text. The parser then needs to convert the text to BBcode.

**Comment by Ev1lbl0w** [comment]
Yes, I used Yarn as an example of the syntax we could have, but we'll only use features we need, which I believe is some branching dialog, trainer's name, etc... What I wanted to exemplify with Yarn is the ease of writing dialogue to *non-developers*. The implementation of it is never tied to an engine or language.

Regarding custom text *(things like color, timing, bold and italic)*, we should then define how we want to write files. We'll have to make a parser anyway, so IMO it's better to use either a format that's easy and not cumbersome to write *(like Markdown, for example)*, or a format Godot already uses, so the parser takes less time to make *(like BBCode)*, and then we add on top some features we want for our game *(such as text delay, variables, etc...)*

**Comment by acedogblast** [comment]
Oh so you want to make a syntax based of of Yarn. That is a good idea. See if you can still have it on a CSV file.

**Comment by Ev1lbl0w** [comment]
Just a reminder: every task here is already implemented in master.
